### PR TITLE
Maybe add @vladar

### PR DESCRIPTION
**Pull request by spawnia**
@IvanGoncharov do not merge just yet, awaiting confirmation.

@vladar i invite you to join this working group meeting. As the primary maintainer of graphql-php and the related server tools, i am sure you could contribute greatly to the discussion.

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@vladar It would be great to have you 👍 
I just need your confirmation and I will merge this PR.

**Comment by vladar** [comment]
Cool, I'm in %)

**Comment by vladar** [comment]
Location is `Tomsk, Russia` at the moment

**Comment by IvanGoncharov** [comment]
@vladar @spawnia We had problem with Zoom here is new link: 
https://meet.google.com/gop-aqar-ssv

**Comment by vladar** [comment]
Sorry, I didn't make it in time - stuck in the other meeting at work, which just ended.

**Comment by IvanGoncharov** [comment]
@vladar No problem, it's was mainly an introductory call but we agreed on a few points see #39 
Also, we will have next call on [Dec 17, 2019 at 19:00 - 21:00 UTC](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2019&month=12&day=17&hour=19&min=0&sec=0&p1=224&p2=179&p3=136&p4=37&p5=239&p6=101&p7=152)

**Pull request merged**
